name: PR checks
on:
  pull_request:
    branches:
      - master
jobs:
  Run-CI-Script:
    runs-on: [self-hosted, medium, amd64]
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '2.7'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: actions/checkout@v2
      - run: scripts/ci.sh
