name: PR checks
on:
  pull_request:
    branches:
      - master
jobs:
  Run-CI-Script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: actions/checkout@v4
      - run: scripts/ci.sh
